name: Merge Playwright reports

on:
  workflow_call:
    inputs:
      artifact_pattern:
        description: 'Pattern to match blob report artifacts'
        required: false
        type: string
        default: 'playwright-blob-shard-*'
      retention_days:
        description: 'Number of days to retain the merged report'
        required: false
        type: number
        default: 14
      node_version_file:
        description: 'Node version file'
        required: false
        type: string
        default: '.nvmrc'

permissions:
  contents: read

jobs:
  merge_reports:
    name: Merge reports
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version-file: ${{ inputs.node_version_file }}

      - name: Install Playwright
        run: npm install @playwright/test

      - name: Download blob reports
        uses: actions/download-artifact@v6
        with:
          pattern: ${{ inputs.artifact_pattern }}
          path: all-blob-reports
          merge-multiple: true

      - name: Merge reports
        run: npx playwright merge-reports --reporter html ./all-blob-reports

      - name: Upload merged report
        uses: actions/upload-artifact@v5
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: ${{ inputs.retention_days }}
